# ============================================================
# PaySign plugin configuration
# ============================================================

name: '${project.name}'
version: '${project.version}'
main: net.nightzy.paysign.PaySignPlugin
api-version: '${apiVersion}'
authors:
  - Drago <drago.klaudiusz@gmail.com>
website: '${project.url}'
description: "Sign payments for using redstone mechanisms."
depend:
  - Vault

# ============================================================
# Permissions
# ============================================================
permissions:
  # Full access
  nightzypaysign.*:
    description: "Gives access to all PaySign commands and usage."
    default: op
    children:
      nightzypaysign.create: true
      nightzypaysign.create.other: true
      nightzypaysign.use: true

  # Create your own payment signs
  nightzypaysign.create:
    description: "Allows creating payment signs."
    default: true

  # Create payment signs for other players
  nightzypaysign.create.other:
    description: "Allows creating payment signs for other players."
    default: true

  # Use payment signs
  nightzypaysign.use:
    description: "Allows using payment signs."
    default: true
