name: '${project.name}'
version: '${project.version}'
authors: ${authors}
website: '${project.url}'
main: pl.lunarhost.paysign.PayBySignPlugin
api-version: '${apiVersion}'
description: Sign payments for using redstone mechanisms.
depend: [Vault]

permissions:
  paybysign.*:
    description: 'Gives access to everything.'
    default: op
    children:
    - paybysign.create
    - paybysign.create.other
    - paybysign.use
  paybysign.create:
    description: 'Gives access to create payment signs.'
    default: true
  paybysign.create.other:
    description: 'Gives access to create payment signs for other players.'
    default: true
  paybysign.use:
    description: 'Gives access to use payment signs.'
    default: true
